/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApplianceType = { 'HobChula' : null } |
  { 'Chimney' : null } |
  { 'Dryer' : null } |
  { 'WashingMachine' : null } |
  { 'Microwave' : null } |
  { 'Dishwasher' : null };
export interface Booking {
  'id' : BookingId,
  'status' : BookingStatus,
  'serviceType' : ServiceType,
  'name' : string,
  'description' : string,
  'email' : string,
  'preferredDate' : string,
  'address' : string,
  'timestamp' : bigint,
  'applianceType' : ApplianceType,
  'phone' : string,
}
export interface BookingCounts {
  'cancelled' : bigint,
  'pending' : bigint,
  'completed' : bigint,
  'confirmed' : bigint,
}
export type BookingId = bigint;
export interface BookingRequest {
  'serviceType' : ServiceType,
  'name' : string,
  'description' : string,
  'email' : string,
  'preferredDate' : string,
  'address' : string,
  'applianceType' : ApplianceType,
  'phone' : string,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export type ServiceType = { 'Repair' : null } |
  { 'Servicing' : null } |
  { 'Installation' : null };
export interface Testimonial {
  'id' : bigint,
  'content' : string,
  'author' : string,
  'timestamp' : bigint,
  'rating' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTestimonial' : ActorMethod<[string, string, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBooking' : ActorMethod<[BookingRequest], BookingId>,
  'deleteBooking' : ActorMethod<[BookingId], undefined>,
  'deleteTestimonial' : ActorMethod<[bigint], undefined>,
  'getBookingCounts' : ActorMethod<[], BookingCounts>,
  'getBookings' : ActorMethod<[], Array<Booking>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'updateBookingStatus' : ActorMethod<[BookingId, BookingStatus], undefined>,
  'updateTestimonial' : ActorMethod<
    [bigint, string, string, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];